In [2]:
import requests
import pandas as pd
import time
from secret import api_key

In [31]:
def get_video_info(video_id):
    #collection views, comments, and likes
    url_video_stat = 'https://www.googleapis.com/youtube/v3/videos?id='+video_id+'&part=statistics&key='+api_key
    response_video_stats = requests.get(url_video_stat).json()

    view_count = response_video_stats['items'][0]['statistics']['viewCount']
    like_count = response_video_stats['items'][0]['statistics']['likeCount']
    #dislike_count = response_video_stats['items'][0]['statistics']['dislikeCount']
    comment_count = response_video_stats['items'][0]['statistics']['commentCount']
    
    return view_count,like_count,comment_count

In [35]:
def get_videos(youtube_df):

    user = 'UCX6OQ3DkcsbYNE6H8uQQuVA' #mrbeast
    #making API call
    pageToken = ''
    url = 'https://www.googleapis.com/youtube/v3/search?key='+api_key+'&channelId='+user+'&part=snippet,id&order=date&maxResults=1000'+pageToken
    #url = 'https://www.googleapis.com/youtube/v3/channels?key='+api+'&forUsername=MrBeast&part=id'

    response = requests.get(url).json()
    time.sleep(1) #to ensure all data has been received before jumping in for loop
    for video in response['items']:
        if video['id']['kind'] == 'youtube#video':
            video_id = video['id']['videoId']
            video_title = video['snippet']['title']
            upload_date = video['snippet']['publishedAt']
            upload_date = upload_date.split('T')[0]

            view_count,like_count,comment_count = get_video_info(video_id)        
            #Using a dictionary to save features to add to DF
            features = {'video_id' : video_id,
                'video_title' : video_title,
                'upload_date' : upload_date,
                'view_count' : view_count,
                'like_count' : like_count,
                'comment_count' : comment_count, 
                }
            
            #concatenate original youtube_df with new DF that contains all features.
            #ignore_index resets index of new DF
            youtube_df = pd.concat([youtube_df, pd.DataFrame(features, index=[0])], ignore_index=True)
    return youtube_df

In [37]:
youtube_df = pd.DataFrame(columns=['video_id','video_title', 'upload_date', 'view_count','like_count', 'comment_count'])

youtube_df = get_videos(youtube_df)

,video_id,video_title,upload_date,view_count,like_count,comment_count
0,lglIQkCHO0g,Do Men Lie About Their Height?,2023-02-14,37010026,2408059,10239
1,TJ2ifmkGGus,"1,000 Blind People See For The First Time",2023-01-28,115213739,8752480,373588
2,7IKab3HcfFk,I Survived 50 Hours In Antarctica,2022-12-24,97802637,3997727,150108
3,h5NvTTOlOtI,Hydraulic Press Vs Lamborghini,2022-12-10,121496449,4554741,128488
4,se50viFJ0AQ,Would You Fly To Paris For A Baguette?,2022-12-08,573130274,29323506,62132

In [38]:
youtube_df

,video_id,video_title,upload_date,view_count,like_count,comment_count
0,lglIQkCHO0g,Do Men Lie About Their Height?,2023-02-14,37010026,2408059,10239
1,TJ2ifmkGGus,"1,000 Blind People See For The First Time",2023-01-28,115213739,8752480,373588
2,7IKab3HcfFk,I Survived 50 Hours In Antarctica,2022-12-24,97802637,3997727,150108
3,h5NvTTOlOtI,Hydraulic Press Vs Lamborghini,2022-12-10,121496449,4554741,128488
4,se50viFJ0AQ,Would You Fly To Paris For A Baguette?,2022-12-08,573130274,29323506,62132
5,0CTp1a-aCUM,"100 Kids Vs 100 Adults For $500,000",2022-12-03,119758185,3267644,94047
6,FD-0KG-h2-c,Gordon Ramsay Tries Most Expensive Chocolate Bar!,2022-11-19,137652378,8995849,22144
7,kX3nB4PpJko,"Last To Take Hand Off Jet, Keeps It!",2022-11-12,93454880,3375324,104281
8,YlvcFJOE-OE,Giving iPhones Instead Of Candy on Halloween,2022-11-02,446166096,18473275,75332
9,iogcY_4xGjo,"$1 vs $1,000,000 Hotel Room!",2022-10-22,172628489,5153998,110751
10,S_CUEOBZ0P4,"The Rock Vs MrBeast For $100,000",2022-10-21,225713213,16657430,49374
11,gHzuabZUd6c,"Survive 100 Days In Circle, Win $500,000",2022-09-24,140505472,3936450,91433
12,65fN_OUawjk,I Hunted 100 People!,2022-09-03,77358144,2650598,66015
13,jdMNoQE3mIQ,I Survived A Plane Crash,2022-08-20,92691166,3060613,77553
14,2isYuQZMbdU,"I Gave My 100,000,000th Subscriber An Island",2022-08-04,115583047,4927833,234154
15,tVWWp1PqDus,"100 Girls Vs 100 Boys For $500,000",2022-07-23,124144249,3753504,141976
16,vaIgyRoUkQI,I Didn’t Eat Food For 30 Days,2022-07-02,71119430,3082546,105734
17,Hwybp38GnZw,I Built Willy Wonka&#39;s Chocolate Factory!,2022-06-04,164881337,5363691,170138
18,hD1YtmKXNb4,"$10,000 Every Day You Survive Prison",2022-04-09,146867297,4462880,146304
19,LnlKwzc_TNA,"Would You Swim With Sharks For $100,000?",2022-03-19,121569932,3496558,98547
20,3jS_yEK8qVI,World’s Most Dangerous Escape Room!,2022-01-29,177639847,4707477,143347
21,00NgUctWoLQ,"Extreme $1,000,000 Hide And Seek",2021-12-18,83929067,3405136,131356
22,x9TQ6culXIA,"$1,000,000 Influencer Tournament!",2021-12-16,69728948,2940860,90566
23,QbJJwaVdgIs,I Got Hunted By The Military,2021-12-10,135742649,3802773,98418
24,0e3GPea1Tyg,"$456,000 Squid Game In Real Life!",2021-11-24,373666744,15578612,616867
25,cV2gBU6hKfY,I Cleaned The World’s Dirtiest Beach #TeamSeas,2021-10-29,89992561,5108546,179477
26,qIsgdOVGA04,"Last To Take Hand Off Lamborghini, Keeps It",2021-10-23,129214822,4092349,131374
27,cExLQ1o2pDw,"First To Rob Bank Wins $100,000",2021-09-26,117158537,3473095,124941
28,uocETPj4Jx4,"Extreme $500,000 Game Of Tag!",2021-09-04,112669980,3764597,102653
29,zxYjTTXc-J8,"Last To Leave Circle Wins $500,000",2021-08-31,265705521,5569339,116660
30,hxwpkM5w3Cc,I Got Hunted By The FBI,2021-08-07,143059677,3703971,95344
31,ktyJIj6i4Qw,"If You Can Carry $1,000,000 You Keep It!",2021-07-24,125929744,3023521,77693
32,urtFrxDUV6c,"Would YOU Quit School For $100,000?",2021-07-10,110228491,2931019,84455
33,nM89Wl03Q4g,I Survived 50 Hours In A Maximum Security Prison,2021-06-26,162549748,3299766,101224
34,NZlClr_ivb4,"Hit The Target, Win $300,000",2021-06-12,126998388,3102096,86751
35,E6E22XQPhhg,Anything You Can Fit In The Triangle I’ll Pay For,2021-06-01,128184066,2854363,87124
36,TQHEJj68Jew,I Got Hunted By A Real Bounty Hunter,2021-04-24,138638363,3555133,127281
37,WcwGleN38zE,"Extreme $100,000 Game of Tag!",2021-04-17,149861852,3110564,120882
38,fMfipiV_17o,"Would You Sit In Snakes For $10,000?",2021-04-10,202563847,4533007,141485
39,ayXxwJJId_c,I Bought The World&#39;s Largest Mystery Box! ...,2021-04-03,170657671,4265717,174696
40,9bqk6ZUsKyA,I Spent 50 Hours Buried Alive,2021-03-27,244618092,7165867,249071
41,DuQbOQwVaNE,"Offering People $100,000 To Quit Their Job",2021-03-13,106676614,3030579,118897
42,vJH28ICkCdU,I Sold My House For $1,2021-03-06,120870750,3462994,118843
43,_uwNDiU04zE,"If You Press This, I’ll Pay...",2021-02-13,50250418,2955953,152845
44,C680oxL__ck,"I Ate $100,000 Golden Ice Cream",2021-01-22,172543865,4766023,172548
45,5Fg9oZk-5uA,I Bought Everything In 5 Stores,2021-01-09,122953619,4702182,192996
46,PKtnafFtfEo,"Youtube Rewind 2020, Thank God It&#39;s Over",2021-01-01,66548708,4986620,289970
47,f0c7pSCoZqE,"I Put 1,000,000,000 Christmas Lights On A Hous...",2020-12-23,83550467,2611310,109663
48,dg2Ag3e8W-Q,I Opened A Restaurant That Pays You To Eat At It,2020-12-19,143614007,4550931,744151
49,LeYsRMZFUq0,"I Gave People $1,000,000 But ONLY 1 Minute To ...",2020-12-15,144492844,5645994,181429